### ISSUE TITLE
Community Toolkit Support

### ISSUE THREAD

**Issue by realybin** [SuperJMN-Zafiro/Zafiro.Avalonia#47]
Can we add the support of Community Toolkit? It seems deeply bindded with reactiveui.

**Comment by SuperJMN** [comment]
Hey @realybin. I'm a firm believer in what ReactiveUI does is the right direction to UI programming. I took a look to Community Toolkit and it looks like a toy compared to it. I'm afraid that lots of things need to change to switch to it.

Thanks for the feedback anyways :)
